name: mongolia

channels:
 - conda-forge
 
dependencies:
- python=3.6
- ipython
- jupyter
- jupyter_contrib_nbextensions
- jupyter_nbextensions_configurator
- notebook
- seaborn 
- patsy 
- pandas
- xlrd
- geopandas
- pip:
    - git+https://github.com/pymc-devs/pymc3.git#egg=pymc3